### ISSUE TITLE
npx create-kaioken@latest should default to npm

### ISSUE THREAD

**Issue by benhalverson** [CrimsonChi/kaioken#15]
**Describe the bug**
npx create-kaioken@latest should default to npm

**To Reproduce**

1. npx create-kaioken@latest
2. follow instructions from cli

**Expected behavior**
expected to see  cd project-name 
npm install
npm run dev

**Comment by LankyMoose** [comment]
closed by https://github.com/CrimsonChi/kaioken/commit/c364e8664ccc410b4497aa12670a569f1e30b856
